### ISSUE TITLE
Clean up code after change to values that are tuples in the action_paths dict.

### ISSUE THREAD

**Issue by thewritingstew** [thewritingstew/cdk#6]
The change to the tuple seems to have affected the 'help' call. Here's the error
 
Traceback (most recent call last):
  File ".\cdk\cdk.py", line 53, in <module>
    main()
  File ".\cdk\cdk.py", line 45, in main
    current_context.display()  # display current context's display
AttributeError: 'str' object has no attribute 'display'

**Comment by thewritingstew** [comment]
Problem is in context.py, _process_input() method. The assignment of dictionary values to the self._goto_context attribute doesn't work for 'help' because the second item in the tuple is not a context object. This means that when the main function tries to use the display() method on the context, an error is returned. 

Possible Fixes
1. create a help context that can be referenced by every other context
2. set the help 'context' slot in the tuple, self.action_paths['help'][1], to False like we do with 'quit' 
3. create self.support_paths attribute that contains the 'help' and 'quit' instructions

**Comment by thewritingstew** [comment]
Created a help context.
